apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapache-svc
  name: webapache-svc
  namespace: apps
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapache
  type: ClusterIP
status:
  loadBalancer: {}
