apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: nginx:1.21-alpine
        name: nginx
        ports:
          - containerPort: 80
            name: 'http'
        resources:
          limits:
            cpu: 30m
            memory: 60Mi
          requests:
            cpu: 10m
            memory: 16Mi
status: {}
