apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-svc
  name: webapp-svc
  namespace: apps
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: ClusterIP
status:
  loadBalancer: {}
