apiVersion: v1
data:
  script.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export const options = {
      stages: [
        { duration: '30s', target: 20 },
        { duration: '1m30s', target: 30 },
        { duration: '20s', target: 0 },
      ],
    };

    export default function () {
      const res = http.get('http://webdic-svc.apps.svc.cluster.local');
      check(res, { 'status was 200': (r) => r.status == 200 });
      sleep(1);
    }
kind: ConfigMap
metadata:
  name: k6job-cm
  namespace: monitoring
