apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-apache
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joaoleau/k8s.git
    targetRevision: HEAD
    path: gitops/hub-apache
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true