apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared-tunnle
  name: cloudflared-tunnle
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-tunnle
  strategy: {}
  template:
    metadata:
      labels:
        app: cloudflared-tunnle
    spec:
      containers:
      - image: leeegiit/cloudflared-tunnel:latest
        name: cloudflared-tunnel
        resources:
          limits:
            memory: 64Mi
            cpu: 30m
          request:
            memory: 32Mi
            cpu: 15m
        env:
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: tunnel-token-secrets
                key: TUNNEL_TOKEN
status: {}
