apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          # requiredDuringSchedulingIgnoredDuringExecution:
          #   nodeSelectorTerms:
          #   - matchExpressions:
          #     - key: role
          #       operator: In #In, NotIn, Exists, DoesNotExist, Gt and Lt.
          #       values:
          #       - infra
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: zone
                    operator: In #In, NotIn, Exists, DoesNotExist, Gt and Lt.
                    values:
                    - us-east-1c
            - weight: 10
              preference:
                matchExpressions:
                  - key: role
                    operator: In #In, NotIn, Exists, DoesNotExist, Gt and Lt.
                    values:
                    - apps
      containers:
      - image: nginx:1.16.1
        name: nginx

