apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipaddresspool
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joaoleau/k8s.git
    targetRevision: main
    path: environment/metallb
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      selfHeal: true

