apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webdic-ingress
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-encrypt"
spec:
  ingressClassName: kong
  rules:
  - host: webdic.leal.services
    http:
      paths:
      - backend:
          service:
            name: webdic-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - secretName: webdic-tls
      hosts:
        - webdic.leal.services

status:
  loadBalancer: {}
