---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Leandro</title>
    </head>
    <body>
      <img src="https://media.licdn.com/dms/image/v2/D4D03AQHmAOGs8N6BQQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1710163148430?e=1757548800&v=beta&t=2Edf9M3JIJKwUpjwirsL1uJ7VhA7I5WlyhPRHHAMgIQ" alt="Imagem Exemplo" />
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-html
  template:
    metadata:
      labels:
        app: nginx-html
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: simple-html
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-html-svc
spec:
  selector:
    app: nginx-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-html-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: leandro.nitrivus.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-html-svc
                port:
                  number: 80
