apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: color-svc
  name: color-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    color: red
  type: ClusterIP
status:
  loadBalancer: {}
