apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"nginx"},"name":"nginx","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.1","name":"nginx","resources":{}}]}}},"status":{}}
  creationTimestamp: "2025-03-07T13:33:12Z"
  generation: 4
  labels:
    app: nginx
    label: legal
  name: nginx
  namespace: default
  resourceVersion: "559961"
  uid: b9e382e5-594b-4d12-8ee3-3e473c48df4a
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        revision: "3"
    spec:
      containers:
      - image: nginx:1.16.1
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2025-03-07T13:34:51Z"
    lastUpdateTime: "2025-03-07T13:34:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-07T13:33:12Z"
    lastUpdateTime: "2025-03-07T13:41:01Z"
    message: ReplicaSet "nginx-6786f6794" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
