apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: private-pool
spec:
  addresses:
    - 192.168.56.100-192.168.56.110
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
spec:
  interfaces:
    - eth1
