apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-subnet-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.20.0.140-172.20.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: private-subnet-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - private-subnet-pool