apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3 #0 Não armazena histórico nenhum
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 10 #Tempo em segundos de tolerância de atraso no Schedule, padrão < 100 tentativas de schedule ('digamos que infinitokkk')
  concurrencyPolicy: Allow #Forbid e Replace - Policies para caso algum job do cron ainda estiver em execução 
  jobTemplate:
    spec:
      completions: 1
      parallelism: 2
      completionMode: NonIndexed
      backoffLimit: 10
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: python:slim
            name: job-fly
            command:
              - python3
              - -c
              - |
                import random
                import sys
                import time
                import os

                numero = random.randint(1, 3)

                if numero == 2:
                    print("Erro: O numero sorteado foi 2")
                    time.sleep(120)
                    sys.exit(1)
                if numero == 3:
                    print("Erro: O numero sorteado foi 3")
                    time.sleep(120)
                    sys.exit(1)    
                else:
                    print("Completed: Estagiario ta voando")
                    sys.exit(0)  
            resources: {}
          restartPolicy: Never