# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-main
#   namespace: cert-manager
# spec:
#   acme:
#     server: "https://acme-v02.api.letsencrypt.org/directory"
#     email: abc@gmail.com
#     privateKeySecretRef:
#       name: letsencrypt-tls
#     solvers:
#     - http01:
#         ingress:
#           ingressClassName: kong
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-encrypt
spec:
  selfSigned: {}