apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    color: red
  name: red
spec:
  replicas: 2
  selector:
    matchLabels:
      color: red
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        color: red
    spec:
      containers:
      - image: nginx:latest
        name: red
        resources: {}
        ports:
          - containerPort: 80
        volumeMounts:
          - name: red-cm
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
      volumes: 
        - name: red-cm
          configMap:
            name: red-cm
status: {}
