kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tururu
nodes:
  - role: control-plane
    labels:
      role: plane
    extraPortMappings:
      - containerPort: 6443
        hostPort: 6443
        protocol: TCP
  - role: worker
    labels:
      zone: us-east-1
      role: apps
  - role: worker
    labels:
      zone: sa-east-1
      role: apps
  - role: worker
    labels:
      zone: sa-east-1
      role: infra
